### ISSUE TITLE
Latest version of nyxx (4.x) creates conflict with nyxx_lavalink when installing

### ISSUE THREAD

**Issue by rilysh** [nyxx-discord/nyxx_lavalink#11]
**Describe the bug**
After installing nyxx, when I try to install nyxx_lavalink it seems conflict with latest version of nyxx.

**To Reproduce**
1. Install nyxx by `dart pub add nyxx`
2. Now try to install `nyxx_lavalink`

**Expected behavior**
nyxx_lavalink version should be updated with nyxx, therefore no conflict issue should be happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/71683721/184524060-9513ddc0-4546-4652-9e45-e72337eb0af5.png)

**Desktop (please complete the following information):**
 - OS: Debian 11 5.10.0-16-amd64
 - Dart version: 2.17.6
 - Nyxx version: 4.0.0
 - nyxx_lavalink version: 3.0.1

**Additional context**
Right now nyxx latest version is 4.0.0 and nyxx_lavalink seems stuck in nyxx 3.4.2. Installing only `nyxx_lavalink` does works. However, it installs older version of nyxx (3.4.2). Seems like nyxx_lavalink needs to bump the version of nyxx with current one.

**Comment by jr1221** [comment]
Add to pubspec.yaml:
```
dependency_overrides:
  nyxx: ^4.0.0
```
nyxx_lavalink hasn't been updated to support 4.0.0 yet, but I tested it out and I think there are no breaking changes for this package.
